Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"

  config.vm.provider "virtualbox" do |v|
    v.name = "Fusion 360"
    v.gui = true
    v.memory = 6144
    v.cpus = 4
    v.customize ["modifyvm", :id, "--graphicscontroller", "vboxsvga"]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--accelerate3d", "off"]
  end

  config.vm.synced_folder "#{ENV["HOME"]}/code/cad", "/cad"

  config.vm.provision :shell, powershell_args: "-NoProfile -ExecutionPolicy Bypass",
    inline: "if (!(Test-Path \"$env:SystemDrive\\ProgramData\\Chocolatey\\bin\")) { iex ((new-object net.webclient).DownloadString('https://chocolatey.org/install.ps1')) }"

  config.vm.provision :shell,
    inline: "chocolatey feature enable -n=allowGlobalConfirmation"

  config.vm.provision :shell,
    inline: "chocolatey upgrade autodesk-fusion360"
end
