" No vi compatibility
if &compatible
    set nocompatible
endif

if !has('nvim')
    " Use XDG dir for .vim
    exec 'set runtimepath='.$VIMDIR.','.$VIMRUNTIME.',/usr/share/vim/vimfiles'
else
    set runtimepath^=$VIMDIR
endif

" Packages
exec 'set packpath='.&runtimepath
packloadall
helptags ALL
function PackAddFor(dir)
    for pkg in split(system('ls '.$VIMDIR.'/pack/'.a:dir.'/opt'))
        exec 'packadd '.pkg
    endfor
endfunction
autocmd FileType * call PackAddFor(&filetype)

" Use a POSIX shell to avoid confusing plugins
set shell=/bin/sh

" Paste without manic indentation
let &t_SI .= "\<Esc>[?2004h"
let &t_EI .= "\<Esc>[?2004l"
inoremap <special> <expr> <Esc>[200~ XTermPasteBegin()
function! XTermPasteBegin()
    set pastetoggle=<Esc>[201~
    set paste
    return ""
endfunction

" Semicolon -> :
nnoremap ; :
vnoremap ; :

" Plugin mappings
nmap s <Plug>(easymotion-jumptoanywhere)
nnoremap <Leader>u :UndotreeToggle<CR>
nnoremap <C-P> :GFiles --cached --others --exclude-standard<CR>
command! -bang -nargs=* BLines
  \ call fzf#vim#buffer_lines(
  \   {
  \     'options': '--delimiter="	" --preview-window="+{1}/2" --preview="bat --highlight-line={1} ' . expand('%:p') . '"'
  \   },
  \   <bang>0
  \ )
nmap f :BLines<CR>
nnoremap <C-C> :Commits<CR>
command! -bang -nargs=* Buffers
  \ call fzf#vim#buffers(
  \   {
  \     'options': '--delimiter="	" --preview="bat {-1}"'
  \   },
  \   <bang>0
  \ )
nnoremap <C-B> :Buffers<CR>
command! -bang -nargs=* Rg
  \ call fzf#vim#grep(
  \   'rg --column --line-number --no-heading --color=always --smart-case '.shellescape(<q-args>),
  \   1,
  \   {
  \     'options': '--delimiter=: --nth=4.. --preview-window="+{2}/2" --preview="bat --highlight-line={2} {1}"'
  \   },
  \   <bang>0
  \ )
nnoremap <C-F> :Rg<CR>

set wildmode=longest,list,full
set wildmenu

" Backspace
set backspace=indent,eol,start

" Statusline
set laststatus=2
let g:airline_theme='term'
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=1
let g:airline_mode_map = {
    \ '__' : '-',
    \ 'n'  : 'N',
    \ 'i'  : 'I',
    \ 'R'  : 'R',
    \ 'c'  : 'C',
    \ 'v'  : 'V',
    \ 'V'  : 'V',
    \ '' : 'V',
    \ 's'  : 'S',
    \ 'S'  : 'S',
    \ '' : 'S',
\ }
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols = get(g:, 'airline_symbols', {})
let g:airline_symbols.branch = ''
let g:airline_symbols.linenr = ''
let g:airline_symbols.readonly = ''

" Syntax
syntax enable
filetype plugin indent on

" Concealing
autocmd InsertEnter *.* set conceallevel=0
autocmd InsertLeave *.* set conceallevel=2
set concealcursor=

" Where am I
set ruler
set cursorline
set number

" Soft tabs, 4sp
set tabstop=4
set shiftwidth=4
set shiftround
set expandtab
let g:indentLine_color_term=239
autocmd InsertEnter *.* let g:indentLine_char=''
autocmd InsertLeave *.* let g:indentLine_char='┊'

" Maintain context
set scrolloff=10
nnoremap <C-I> <C-I>zz
nnoremap <C-O> <C-O>zz
nnoremap { {zz
nnoremap } }zz
autocmd BufEnter * normal! zz

" Highlight search terms
nnoremap <Leader>l :nohlsearch<Return>
set hlsearch
set incsearch

" Reload changes on disk
set autoread
autocmd FocusGained * checktime
