[buildPlans.myosevka]
family = "Iosevka Myosevka"
spacing = "fontconfig-mono"
serifs = "sans"

[buildPlans.myosevka.variants.design]
a = "doublestorey"
g = "opendoublestorey"
i = "serifed"
l = "zshaped"
m = "shortleg"
t = "standard"
q = "tailed"
ampersand = "et-toothed"
asterisk = "low"
at = "short"
brace = "straight"
caret = "high"
dollar = "through"
eszet = "sulzbacher"
number-sign = "upright"
paragraph-sign = "high"
tilde = "low"
underscore = "low"
zero = "slashed"

[buildPlans.myosevka.variants.upright]
i = "zshaped"
l = "zshaped"

[buildPlans.myosevka.variants.italic]
i = "hooky"
l = "hooky"
brace = "curly"

[buildPlans.myosevka.ligations]
inherits = "clike"
