[buildPlans.Myosevka]
family = "Iosevka Myosevka"
spacing = "fontconfig-mono"
serifs = "sans"

[buildPlans.Myosevka.iosevka-generate]
nerdfont = ["complete"]

[buildPlans.Myosevka.variants.design]
# Numbers
one = "no-base"
three = "flat-top-serifless"
four = "semi-open-serifless"
seven = "straight-serifless-crossbar"

# Letters
a = "double-storey-tailed"
d = "toothed-serifless"
f = "flat-hook-tailed"
g = "double-storey"
h = "straight-serifless"
i = "serifed"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "zshaped"
m = "short-leg-serifless"
q = "tailed-serifless"
capital-q = "crossing"
r = "serifless"
capital-r = "curly-serifless"
t = "flat-hook-short-neck"
v = "straight-serifless"
w = "straight-serifless"
y = "straight-serifless"
z = "straight-serifless-with-horizontal-crossbar"

# Symbols
ampersand = "et-toothed"
ascii-grave = "straight"
asterisk = "penta-low"
at = "compact"
brace = "straight"
bar = "force-upright"
caret = "high"
dollar = "through"
eszet = "sulzbacher-descending-serifless"
lower-lambda = "straight"
lig-ltgteq = "slanted"
number-sign = "upright"
pilcrow= "high"
paren = "normal"
percent = "dots"
tilde = "low"
underscore = "high"
zero = "slashed"

[buildPlans.Myosevka.variants.upright]
i = "zshaped"
l = "zshaped"

[buildPlans.Myosevka.variants.italic]
i = "hooky"
l = "hooky"
brace = "curly"

[buildPlans.Myosevka.ligations]
inherits = "clike"

[buildPlans.Myosevka.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Myosevka.widths.Normal]
shape = 500
menu = 5
css = "normal"
