[buildPlans.myosevka]
family = "Iosevka Myosevka"
spacing = "fontconfig-mono"
serifs = "sans"

[buildPlans.myosevka.variants.design]
# Numbers
one = "no-base"
three = "flat-top"
four = "semi-open"
seven = "straight-crossbar"

# Letters
a = "double-storey-tailed"
d = "toothed-serifless"
f = "flat-hook-tailed"
g = "double-storey"
h = "straight"
i = "serifed"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "zshaped"
m = "short-leg"
r = "serifless"
capital-r = "curly"
t = "flat-hook-short-neck"
turn-v = "straight"
w = "straight"
q = "tailed"
capital-q = "crossing"
y = "straight"
z = "straight-serifless-with-horizontal-crossbar"

# Symbols
ampersand = "et-toothed"
ascii-grave = "straight"
asterisk = "penta-low"
at = "short"
brace = "straight"
bar = "force-upright"
caret = "high"
dollar = "through"
eszet = "sulzbacher"
lower-lambda = "straight"
lig-ltgteq = "slanted"
number-sign = "upright"
pilcrow= "high"
paren = "normal"
percent = "dots"
tilde = "low"
underscore = "high"
zero = "slashed"

[buildPlans.myosevka.variants.upright]
i = "zshaped"
l = "zshaped"

[buildPlans.myosevka.variants.italic]
i = "hooky"
l = "hooky"
brace = "curly"

[buildPlans.myosevka.ligations]
inherits = "clike"
