[buildPlans.myosevka]
family = "Iosevka Myosevka"
spacing = "fontconfig-mono"
serifs = "sans"

[buildPlans.myosevka.variants.design]
# Numbers
one = "nobase"
three = "flattop"
four = "semi-open"
seven = "crossbar"

# Letters
a = "doublestorey"
d = "toothed"
f = "flat-hook-tailed"
g = "doublestorey"
h = "straight"
i = "serifed"
j = "flat-hook-serifed"
k = "curly"
l = "zshaped"
m = "shortleg"
r = "straight"
capital-r = "curly"
t = "flat-hook-short-neck"
turn-v = "straight"
w = "straight"
q = "tailed"
capital-q = "crossing"
y = "straight"
z = "with-horizontal-crossbar"

# Symbols
ampersand = "et-toothed"
ascii-grave = "straight"
asterisk = "low"
at = "short"
brace = "straight"
bar = "force-upright"
caret = "high"
dollar = "through"
eszet = "sulzbacher"
lambda = "straight"
lig-ltgteq = "slanted"
number-sign = "upright"
paragraph-sign = "high"
paren = "normal"
percent = "dots"
tilde = "low"
underscore = "high"
zero = "slashed"

[buildPlans.myosevka.variants.upright]
i = "zshaped"
l = "zshaped"

[buildPlans.myosevka.variants.italic]
i = "hooky"
l = "hooky"
brace = "curly"

[buildPlans.myosevka.ligations]
inherits = "clike"
