auth {
    fingerprint {
        enabled = true
    }

    pam {
        enabled = true
        module = hyprlock
    }
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 3
    color = rgba(0, 0, 0, 0)
}

general {
    hide_cursor = true
    screencopy_mode = 0
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeOut, 1, 5, linear
}
